SD_DSC.adoc
cPP_DSC.adoc

This is the change for the DSC0002 TD applied to the adoc

Changes for the DSC0002 TD

---

cPP_DSC.adoc

cPP atsec/6 fix

---

SD_DSC.adoc

This is to close #87, close #95, close #89, close #97, close #107, close #58, close #52, and close #55.

CCDB SD editorial changes

---

SD_DSC.adoc

This is to implement the change for TD DSC0005

TD DSC0005

---

cPP_DSC.adoc

This is to close #6, close #8, close #9, close #40 and close #41.
These are simple editorial changes.

cPP editorials

---

SD_DSC.adoc

This is to close #18, close #19, close #21, close #25, close #26, close #27, close #28, and close #29

atsec editorial SD changes

---

cPP_DSC.adoc

allowed-with update

---

SD_DSC.adoc

This is to close #46, close #47, close #50 and close #96.

GE-focused updates

---

SD_DSC.adoc

ava_van.1-6

---

SD_DSC.adoc

This is to close #100 and close #101.

AU updates

---

SD_DSC.adoc
cPP_DSC.adoc

This change is to close #70 and to close #71

FPT_PHP.3 updates

---

cPP_DSC.adoc

app note update
This is to close #39.

debug modes

---

SD_DSC.adoc
cPP_DSC.adoc

FDP_SDC.2 update

---

SD_DSC.adoc
cPP_DSC.adoc

This reverts commit 90540dbf8e81da985eb43e9afc03af65b6bae799.

Revert "FMT_SMR.2 -> FMT_SMR.1"

---

cPP_DSC.adoc

This is just a review to correct minor edits that need to be resolved (like pointing to the current SFR)

minor crypto fixes

---

cPP_DSC.adoc

This is to close #32. The text has been updated to emphasize local storage vs transmission (for propagate).

update storage description

---

cPP_DSC.adoc

Key storage updates

---

SD_DSC.adoc
cPP_DSC.adoc

Edit permanent and persistent

---

cPP_DSC.adoc

This is to remove some of the selections that don't make sense for a DSC and close #154.
May still need some further tweaking on the text in here, but this should work overall.

FCS_CKM_EXT.3 selections

---

cPP_DSC.adoc

This is to close #185 by moving the table into the appendices instead of in the middle of the SFRs.

sfr arch table move

---

cPP_DSC.adoc

This is to close #189 on the aspect that the sentence doesn't make any sense in the SFR app note.

confidentiality update

---

cPP_DSC.adoc

fpt_pro_ext.1 app note

---

cPP_DSC.adoc

Attempt to better write the roles. Still needs more review, but should be most of the way there.

editing of roles

---

cPP_DSC.adoc

immutable rollback

---

cPP_DSC.adoc

change "one root of trust" to "a root of trust"
This is to close #198

RoT change

---

cPP_DSC.adoc

This is to close #195. I tried to clarify as much as I could, and remove some of the points about what can change. I also removed the column about permissive/restrictive from the table as I don't think that was useful. 
I don't really think more can be done here without a lot more changes regarding SDO edits as in #179, but I also think we may not have time to really deal with that.

Update to FMT_MSA.3 app note (#2)

---

SD_DSC.adoc
cPP_DSC.adoc

this is to close #214.
There are no changes to any text, only the location of the sections and changing FDP to FPT.

FPT_MFW edits

---

SD_DSC.adoc

tweak to the intro where the SD stated it could be supporting multiple cPPs, then had a list for the cPP. Took out the version from the sentence, created a different issue to add that into a table in the Foreward (#247)

tweak to intro

---

cPP_DSC.adoc

The app note did not specify all the algorithm SFRs that are listed in the selection.

FDP_DSI.2 edit

---

SD_DSC.adoc

SD FMT review (mandatory)

---

cPP_DSC.adoc

This is to respond to @slpotte in https://github.com/DSC-iTC/cPP/pull/254#issuecomment-2077442926.
This doesn't address users/roles

Section 2.4 update

---

SD_DSC.adoc

This is a set of changes for the SD in the FDP requirements. Nothing major, mostly editorial.

SD updates for FDP (mandatory)

---

SD_DSC.adoc
cPP_DSC.adoc

Some testing updates for the FPT EAs

SD FPT review (mandatory)

---

SD_DSC.adoc
cPP_DSC.adoc

FIA_SOS.2 update

---

SD_DSC.adoc
cPP_DSC.adoc

This is to partially close #125 and to close #247

CC References update

---

SD_DSC.adoc

This is to close #282. I think with these updates that the overall testing is clear enough.

FPT_ITT.1 test update

---

cPP_DSC.adoc

These are based on further feedback from the crypto wg.
These are based on comments from @slpotte to the many comments from #308.
I am trying to make the adjustments here instead of reopening that pull request for further work.

minor crypto updates

---

cPP_DSC.adoc

FCS_CKM_EXT.7 app note

---

cPP_DSC.adoc

example table

---

cPP_DSC.adoc

Looking at the actual text of FTP_CCMP_EXT.1, CCMP-256 (IEEE 802.11ac) is also allowed.

Add reference for CCMP-256

---

cPP_DSC.adoc

This set of changes is specific to the errata 1.1 update. The changes all seemed to revolve around FCS_RBG as far as the changes that apply to the DSC are concerned.

Errata v1.1 update

---

SD_DSC.adoc
cPP_DSC.adoc

This is focused on the changes to the version/date info so the publication will be clear what version it is (missed this on the last one).

Proposed Draft version update

---

cPP_DSC.adoc

FCS_CKM_EXT diagram

---

cPP_DSC.adoc

FCS_STG_EXT.1 update

---

cPP_DSC.adoc

Per #381 and as discussed during the meeting

Remove last 3 sentences of para 1 in Application 11
