- SD_DSC.adoc
added KMD and adjusted sentence to reference this as the documentation containing the functional specification.
This is to close #91.
> ATE_IND update

- SD_DSC.adoc
This is to close #43.
The text around the open samples was adjusted and now says "may" as opposed to in such cases, so this should be clear that it is not necessary at all.
I removed the sentence about the location of the testing. I think this is something the vendor, lab and scheme will need to work out for an evaluation and putting it here as a statement up front clearly causes a lot of questions about whether this is sufficient or not. Given that the iTC cannot answer the question about it being sufficient adequately for all evaluations and circumstances, I think it is best to remove that sentence and just be clear about the purposes of this test environment, which is really about the samples being used, and should not be about where they are located.
The point about whether all …
> open samples update

- SD_DSC.adoc
- cPP_DSC.adoc
This removes FCS_CKM.1/KEK, but uses that SFR as the FCS_CKM.1 SFR (with appropriate changes).
> Consolidate FCS_CKM.1

- cPP_DSC.adoc
This removes the specific reference to the side channel attacks. It also adjusted the intro to be more explicit about this being targeted to embedded components/systems in a device, and not discrete components like TPMs, HSMs or secure elements which may be included in a device, but are not technically embedded in the same way.
I do not think we have a problem stating this, and if someone really wants to complain about removing secure elements or TPMs from this they can speak up during comments and we can adjust, but I doubt that will happen as this is targeting the middle part between them.
One thing here is that it may be useful to add the definition for Secure Execution Environment that has been defined in the Biometrics PP-Module as a generic term for things like a TEE but which are …
> side-channel

- cPP_DSC.adoc
The catalog FCS_CKM.2 provides "encrypted channels" as an option for the way to transport keys. This has a dependency on FTP_PRO.1, which we don't want to bring in (this was already discussed as a possible edit for CC:2022 and rejected in #148).
The 1.0 has defined FTP_ITP_EXT.1, FTP_ITE_EXT.1 and FTP_ITC_EXT.1 as transport methods so I have adjusted the SFR to point to those methods used for SDEs/SDOs as acceptable key transport methods.
I'm actually not sure we need anything other than the FTP_IPT_EXT.1 for physically protected channels, but this is more complete.
> FCS_CKM.2 encrypted channels

- SD_DSC.adoc
- cPP_DSC.adoc
This is to move the FMT_SMR.2.3 selections out to FDP_ACF.1 and FMT_MOF_EXT.1. After doing that this can be dropped to FMT_SMR.1
> FMT_SMR.2 -> FMT_SMR.1

- SD_DSC.adoc
- cPP_DSC.adoc
This is to change the EXT version to non, using similar language edits as to the other FPT_RPL.
> FPT_RPL_EXT to FPT_RPL

- cPP_DSC.adoc
This is to close #3.
Instead of adding the key wrapping, I adjusted the text to just state it protects integrity and to reference the appropriate objective. This is the only place in the intro (at least this section) where SFRs were actually referenced, so it seemed out of place to have them referenced here and to add KW or GCM.
> key integrity

- cPP_DSC.adoc
This is to close #4. This adds "OS or" to match with the description of the SD. I think this is needed since some DSCs may encompass some sort of OS (like a TEE) that is more than just firmware. This may be a meaningless distinction and OS could be as easily removed from the SD, but when I think firmware I don't tend to think of larger systems like a TEE but smaller ones like on an eSE.
> adding "OS" to DSC description

- cPP_DSC.adoc
Fixes to the column listing to make it aligned again.
This was due to crypto SFR changes and a max of 10 rows per the one left column to enforce better pagination in PDFs, and as the SFRs were changed, it caused some of the number of rows to offset.
> edit to Table 14

- cPP_DSC.adoc
On reading the requirements and comments it seemed that it may be that pre-installed SDOs may not be able to be changed by updates, and splitting it into two separate selections would provide better granularity.
> fmt_smf.1 edit

- cPP_DSC.adoc
This is to close #200 by clarifying that only the RoT identified in the other SFR can be used here.
> fpt_rot_ext.1 update

- cPP_DSC.adoc
This is to close #196 by removing the "extensions" confusion in possible reading where English may not be the first language.
This would also close #202 for the same reason.
> fmt_smf clarification

- cPP_DSC.adoc
Removed the remaining extra paragraphs in the SPD. For some parts moved content into introduction as appropriate.
Also changed the SPD from being in () to bold to make it easier to see the SPD names in the document (to make them stand out).
> SPD cleanup

- cPP_DSC.adoc
This is to close #219 by simplifying the selection to no choice.
As the app note states, the specific options allowed are set in FMT_MSA.3, so also setting them here adds confusion. All the options are specified according toe SDO.Reauth, so there isn't anything else that has to be specified, one of those settings must be used.
> simplify fia_uau.6

- SD_DSC.adoc
This is a base update to the SD that updates the SFRs to match the current cPP and moving some of the requirements around as they have moved to match the cPP.
There are several markers of [IMPORTANT] in the document that point out where the requirements have either been added or changed (such as FCS_CKM.2 changed from establishment to distribution). These would seem to be the primary areas of focus initially since they are as yet undefined.
> Base crypto update to SD

- cPP_DSC.adoc
The app note and the SD both stated that authorization data needed to be protected but this wasn't included in the SFR itself. This makes that explicit.
> FDP_SDC.2.1 hidden requirement

- SD_DSC.adoc
- cPP_DSC.adoc
This is to close #172 based on what the ND iTC did to add the SARs as optional. This is identical to their text except for the headings which I changes to match out style.
> ALC_FLR optional

- cPP_DSC.adoc
This is to close #249 by adding in the reference to FCS_COP.1/KeyEncap.
> FCS_CKM.2 reference

- cPP_DSC.adoc
I think this is all that technically applies from the errata to the cPP (and I don't think we need anything in the SD, though I could certainly be wrong there, but with less copied directly into the SD, that is more likely).
This is to close #291
> CC:2022 Errata update

- cPP_DSC.adoc
As specified in https://github.com/DSC-iTC/cPP/issues/35 the approach of the direct rationale PP/ST shall be taken. The change removes the objectives for the TOE and replaces the objectives to SFR mapping with the SPD to SFR mapping as defined in CC2022 Appendix Part 1 B.5.
The approach to the mapping was to apply the threads mapped to objectives when replacing the objectives in the SFR mapping table.
> Direct rationale PP

- cPP_DSC.adoc
This is the update to incorporate the updated changes from the Crypto WG.
Consider if FCS_CKM_EXT.9 should be included as this is new. It seems like it could be relevant, but it isn't something that is included at the moment, and it isn't clear this is necessary at this time (it could just be added as an optional requirement).
The FCS_COP.1/KeyWrap added CCM & GCM, but there is also a new SFR for FCS_COP.1/AEAD. Instead of including those in the keywrap and duplicating the requirements, I modified the SFRs that we were adding them to the KW for to also point to the AEAD as an option that would meet the requirement.
This is a large set of changes but all are related to integrating the changes from the latest draft.
I put a few questions in #307 that are minor edits.
One big thing here is …
> Crypto v1 update

- cPP_DSC.adoc
For FPT_MFW_EXT.2, the intent seems to be to allow MAC verification. Note the App Note says "The TOE guarantees the integrity of the firmware by verifying its integrity." and later "FCS_COP.1/SigVer applies if the TOE provides the capability to update the TOE firmware and uses digital signatures and MAC verification for update verification."
Obviously, FCS_COP.1/SigVer does not apply for MAC verification, so it should be clarified.
For FPT_MFW_EXT.3, the intent seems to be to only allow signature verification. Note the App Note says "The TOE guarantees the authenticity of the firmware by verifying its signature."
Then, the later reference to "MAC verification" in the App Note needs to be removed.
> Clarify App Notes for FPT_MFW_EXT.2 and FPT_MFW_EXT.3

- cPP_DSC.adoc
The first paragraph of the app note in the catalog is really intended for people using the catalog, not for inclusion in the cPP.
> FCS_CKM.5 app note edit

- SD_DSC.adoc
This is to close #149. This is the only table I could find that didn't have a label that should and so the only thing that seemed relevant here.
> table consistency update

- cPP_DSC.adoc
Two other instances of XTS (FCS_COP.1.1/SKC) refer to the 2018 revision, so I don't see any reason to refer to the old revision here.
> Use latest revision of IEEE standard for XTS

- cPP_DSC.adoc
Per request from Apple legal counsel, remove Apple from the list of acknowledgements for the document.
--------
Brian,
Thank you very much for this offer, Brian.  We would prefer to be removed given our current status.  Thank you for doing this before publishing the next draft.
Jonathan
On Aug 8, 2024, at 11:09 AM, Brian Wood <> wrote:
Sure, we can do that, but given your heavy initial participation, it is still valid that you can be listed as such going forward (the v2.0 we are working on is still based on that work and has a lot of original content from it).
There isn't a problem with doing it, but contributions can be for the past, not just the current.
Please confirm that you do still want to remove it (based on this), and I will do so before the next draft is published.
Thank you …
> Remove Apple from list

- cPP_DSC.adoc
A little pedantic perhaps, but the selection in FIA_AFL_EXT.1.3 is "prevent all future authorization attempts indefinitely (i.e., lock), as described by FIA_AFL_EXT.2"
> Consistent FIA_AFL_EXT.2 app note

- SD_DSC.adoc
- cPP_DSC.adoc
This is to clear out a note that FCS_CKM.2 had been left from the old requirement EA and needed to be updated.
At the same time the cPP requirement was changed to explicitly note the SFRs that need to be specified for encapsulation and wrapping.
> FCS_CKM.2 changes

- cPP_DSC.adoc
This is to close #347
Taking a good look at this, it is a lot of text. I'm rewriting it to look more like the Network Device table where the rationale statements are simpler (things like "SFR included" or other simple statements).
I'm adding DSC-specific dependencies in italics in the lists so they are clearly different than the CC:2022 ones.
One question here is that the catalog excludes FCS_CKM.3 from the dependencies. There is FCS_CKM_EXT.3 which is similar and probably sufficient in general. I'm adding this in for some but not all, though it would seem to mean that that not having it included in any FCS_COP.1 requires an explanation.
Looking at the catalog, the following dependencies seem wrong (in the catalog, the table or both):
FCS_COP.1/KeyedHash - it would seem that …
> updates to the dependency table

- SD_DSC.adoc
- cPP_DSC.adoc
This creates the EA for FCS_CKM_EXT.3 which was a new SFR and had no EA.
> Update FCS_CKM_EXT.3 for SD

- SD_DSC.adoc
This part of the EA isn't related to concatenated keys, but rather the KDF-MAC-2S, so it should be clarified.
Closes #362
> Update FCS_CKM.5 TSS EA

- SD_DSC.adoc
FCS_ENT_EXT is no longer defined in the cPP. There is no reason to have it in the SD.
> Remove FCS_ENT_EXT from SD

- SD_DSC.adoc
- cPP_DSC.adoc
FCS_OTV_EXT.1 replaced FCS_SLT_EXT.1 and is now more general. Its references in the SD as well as in some other places in the DSC should be updated.
> Generalize FCS_OTV_EXT.1

- cPP_DSC.adoc
The wording for this attribute was a bit inconsistent. I arbitrarily chose one wording and replaced all others throughout the cPP. The SD does not mention this attribute.
> SDO.Conf wording consistency

- SD_DSC.adoc
- cPP_DSC.adoc
This is to close #372.
The point of this change is to be minimally invasive and to point to other tests that would actually verify the underlying activities to support this SFR. The only dependency listed in FCS_COP.1, but based on how the cPP is designed FPT_PHP.3 is needed as well (and FCS_STG_EXT.1.1 ties what is needed where, sort of, but the closest we have).
> FDP_DSC.2 EA

- cPP_DSC.adoc
This is to close #370.
The logic here is that selecting the software storage does not explicitly mandate the use of FCS_CKM_EXT.3, but that is the intent. Having this as an app note is a hidden requirement and is not allowed. By adding in the statement that protection of software-based storage has to be according to that SFR, it makes that requirement visible and explicit.
With that I don't think we actually need to have the app note anymore, since it really doesn't have any reason to be there. We do have this in some other places, but when it is explicit, I think we can drop it.
> FCS_CKM_EXT.3 hidden requirement

- SD_DSC.adoc
- cPP_DSC.adoc
Original comment:
> Application Note 29 states:
> Attributes assigned by the TOE to any parsed SDOs must be described in the Security Target and in operational user guidance.
> However, there is no corresponding guidance EA for FMT_MSA.3 in section 2.4.2.2.
> Either remove the requirement for the operational user guidance from Application Note 29 or include guidance EA.
I added it to the guidance EA, and also made it more explicit in the TSS EA.
> FMT_MSA.3 SD consistency

- cPP_DSC.adoc
As discussed, any application notes that just say  "If X is selected then the selection-based SFR Y must be claimed." can be removed if the SFR text forces the ST author to include it.
Also cleans up some wording and makes the remaining "If X is selected then the selection-based SFR Y must be claimed" application notes consistent (there are still a couple left if it wasn't possible to force the selection in the SFR text). 
Closes #367
> Remove redundant application notes and clean up some wording

- cPP_DSC.adoc
I know it's pretty late in the game but these seemed important enough. The `{empty}` tags were added to fix the rendering.
The SFR text in the actual cPP body will be fixed as part of a separate PR.
> Fix ECD text

- cPP_DSC.adoc
First, update the SFR formatting conventions section as discussed
during the meeting (the most substantial change being that assignment
-> selection refinements won't be bolded completely).
Then, for each SFR, the formatting is updated to match this convention.
The only exceptions are FCS_STG_EXT.1.1, FDP_SDC.2.1, FPT_TST.1.1, due
to other issues.
Note that this PR includes the commits from #385 for my convenience. It should be merged after #385 is merged.
The remaining SFRs are discussed in #386 , #388 , #389 
Closes #378 
Closes #388 
Closes #389
> Sfr formatting

- SD_DSC.adoc
- cPP_DSC.adoc
This is for the final publication date and version.
I am removing the interim releases for the drafts as those aren't needed for the final publication but are useful for the draft release process.
> Publication date/version
